### PR TITLE
Setup for Elmer-OpenFOAM coupling in the flow over heated plate case

### PR DESCRIPTION
**Pull request by arvedes**
I added the setup for the Elmer-OpenFOAM coupling in the flow over heated plate case, a short description is provided in the readme. Due to different naming of the variables in Elmer / OpenFOAM the OpenFOAM-style names have to be hard-coded into the coupler solver. A slightly different preCICE config (compared to the preCICE tutorials) is needed because (as far as I know) Elmer doesn't support capital letters.

### CODE REVIEW

**Comment by BenjaminRodenberg** [comment]
@arvedes: This PR has been lying around for some time. What would you need here? Just somebody to try out the case or do you need an in-depth review?

**Comment by arvedes** [comment]
I didn't make any big changes here, basically I just added my setup that I used to run the case for the preCICE workshop. I tried to describe my workflow in the readme of the Flow_Over_Heated_Plate directory, I hope good enough for a quick trial-and-merge review. Would you like to do that?

Maybe also just a short review of the files changed would be enough, I'm not sure what's the usual procedure in such cases.

**Comment by tapegoji** [comment]
I am very interested in this PR. When this is going to be merged?

**Comment by IshaanDesai** [comment]
> I am very interested in this PR. When this is going to be merged?

The changes from this pull request are ported and included in https://github.com/precice/elmer-adapter/pull/4, right?

**Comment by tapegoji** [comment]
> > I am very interested in this PR. When this is going to be merged?
> 
> The changes from this pull request are ported and included in #4, right?

This is for v2. #4 is for v3. I think they are different. I don't know how you want to address that. Maybe some branch that is suited for v2?

**Comment by uekerman** [comment]
I would recommend to only consider #4 and close this PR. If somebody ever needs it, they can re-open. The work is not lost.

**Comment by IshaanDesai** [comment]
Closing this PR in favor of https://github.com/precice/elmer-adapter/pull/4

**Pull request closed without merging**
